# description: configuration file path, if it's specified as relative path,
# then directory of binary file will be the base directory of configuration file,
# it is recommended to specify absolute path.
# command-line-argument: --config
# type: string
# default: None
config: rsa_default.yaml

# log configuration
log:
  # description: log level
  # command-line-argument: --log-level
  # type: string
  # available: [debug, info, warn, error, fatal]
  # default: info
  level: info
  # description: log format
  # command-line-argument: --log-format
  # type: string
  # available: [text, json]
  # default: text
  format: text
# description: rsa key type
# command-line-argument: --key-type
# type: string
# default: public
keyType: public
# description: rsa key string
# command-line-argument: --key-string
# type: string
# default: None
keyString: ""
# description: input string
# command-line-argument: --input
# type: string
# default: None
input: ""