# description: configuration file path, if it's specified as relative path,
# then directory of binary file will be the base directory of configuration file,
# it is recommended to specify absolute path.
# command-line-argument: --config
# type: string
# default: None
config: rsa_default.yaml

# log configuration
log:
  # description: log level
  # command-line-argument: --log-level
  # type: string
  # available: [debug, info, warn, error, fatal]
  # default: info
  level: info
  # description: log format
  # command-line-argument: --log-format
  # type: string
  # available: [text, json]
  # default: text
  format: text
# rsa configuration
rsa:
  # description: rsa encrypt key type
  # command-line-argument: --rsa-encrypt
  # type: string
  # available: [public, private]
  # default: private
  encrypt: private
  # description: rsa decrypt key type
  # command-line-argument: --rsa-decrypt
  # type: string
  # available: [public, private]
  # default: public
  decrypt: public
  # description: rsa private key
  # command-line-argument: --rsa-private
  # type: string
  # default: None
  private: ""
  # description: rsa public key
  # command-line-argument: --rsa-public
  # type: string
  # default: None
  public: ""
# description: input string
# command-line-argument: --input
# type: string
# default: None
input: ""